print("Las máquinas me sorprenden con mucha frecuencia.")
print()
print("Me interesa saber más de este tema")
print('"23" y',23)
print("Una computadora puede ser llamada \"inteligente\" si logra engañar a una persona haciéndole creer que es un humano.")
print("Carolina","Andrade","19")
print("Carolina","Andrade","19",sep='-')
print("Zapiola \t","500 \t","9400")
print("Zapiola, 500, 9400")
print("Feliz \n","\t Primavera \n","\t \t \t 2024")
print("Solo podemos ver poco del futuro","pero lo suficiente para darnos cuenta de que hay mucho que hacer.",sep=", ")
print("      *")
print("     * *")
print("    *   *")
print("   *     *")
print("  ***   ***")
print("    *   *")
print("    *   *")
print("    *****")

